{
    'name': "Website Sale Search Clear",
    'summary': """Clear the search""",
    'category': 'eCommerce',
    'version': '12.0.1.0.1',
    'application': False,
    'author': 'Mediterranean Apps',
    'license': 'GPL-3',
    "support": "mediterranean.apps@gmail.com",
    'price': 14.0,
    'currency': 'EUR',
    'images': ['images/search.png'],
    'depends': ['website_sale'],
    'data': [],
    'post_load': 'post_load',
    'pre_init_hook': None,
    'post_init_hook': None,

    'auto_install': False,
    "installable": True,
}
